### PR TITLE
Release 1.2.0

### PR DESCRIPTION
**Pull request by benschwarz**
- Added `calibre test download-artifact <uuid>` command.
- Added `calibre site download-snapshot-artifacts --site=<slug> <id>` command.
- Changed `calibre site delete-snapshot` to use `id` rather than `iid`.
- Changed `calibre site get-pulse-metrics` to default to returning data for all pages. (Previously the `--page` flag was required).

Todo: 

- [x] Write a `manifest.json` file to disk along with artifacts for the `download-snapshot-artifacts` command so that people can easily discover the file paths for the newly downloaded files.

### CODE REVIEW

**Comment by benschwarz** [comment]
What's remaining on this?

**Comment by micdijkstra** [comment]
Getting Travis to run the new tests, then I was going to look at adding a few tests for new features.

**Comment by benschwarz** [comment]
After you've merged the graphql/request changes, we'll need to update the CHANGELOG before merging this PR 👍

**Comment by benschwarz** [comment]
I think we're good to go on this?

**Pull request merged**
